### ISSUE TITLE
Add Gemscript operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#112]
This is specific to CPRD analysis in Jigsaw.  The JAM needs a Gemscript operator to query the Drug Exposure table.  It will include source codes.

---
Moved from outcomesinsights/jigsaw#357
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
What is the vocabulary_id for Gemscript?

**Comment by jenniferduryea** [comment]
56

**Comment by aguynamedryan** [comment]
Couple more questions:

- Is it Gemscript or GemScript?
- Do the codes have some sort of formatting we should check for?
  - e.g. ICD-9 has `[EV#]##.##`
- Just to confirm, Gemscript is a Source, not Standard, vocabulary?

**Comment by jenniferduryea** [comment]
> Is it Gemscript or GemScript?
Gemscript

>Do the codes have some sort of formatting we should check for?
it looks numeric but I'm not sure if a zero can precede it

>Just to confirm, Gemscript is a Source, not Standard, vocabulary?
yes

**Comment by markdanese** [comment]
Gemscript in the CPRD data appears to be an 8 digit code in 100% of cases (excluding the one that was missing out of 59,000+ codes).  It was for "unknown" with no product name, or BNF code.

**Comment by markdanese** [comment]
digit = integer, no letters

**Comment by markdanese** [comment]
let me double check that.  length of 8 is correct.  need to check that all are numbers.

**Comment by markdanese** [comment]
no letters.

**Comment by aguynamedryan** [comment]
Awesome.  I've put in a validation so all codes must be exactly 8 digits.

**Comment by jenniferduryea** [comment]
I created an algorithm and ran a study.  Everything worked as expected.  Note that the conceptql vocabulary database does not include Gemscript codes. So every code that you enter into the Gemscript operator will produce a warning because the JAM cannot verify if the code entered is in the provided vocabularies.  We can add Gemscript codes to the JAM vocabularies at another time.  But for now, we should inform the client that every code entered in the operator will produce a warning.  Closing out.
