### ISSUE TITLE
Create CSV file to list all possible vocabularies to pull into the vocabulary operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#121]
Have conceptql read from a csv file to update the list of vocabularies to query for the vocabulary operator.

Logistically, Outins will provide CSV with all available vocabularies and we will post this to Amgen's gitlab.  Amgen will then import the CSV file from gitlab to then update their internal vocabulary operator.

**Comment by aguynamedryan** [comment]
Here is the vocabulary file so far: https://github.com/outcomesinsights/conceptql/blob/master/config/vocabularies.csv

**Comment by jenniferduryea** [comment]
I believe we need to add a domain column in the vocabulary file for OMOP v4.5+ datasets.

**Comment by aguynamedryan** [comment]
@jenniferduryea, do we need to support multiple domains for a single vocabulary?

**Comment by jenniferduryea** [comment]
@aguynamedryan  currently, yes, for READ codes.

**Comment by aguynamedryan** [comment]
Once we move into the territory of multiple values assigned to a single entity, CSV format gets ugly.  In this case, assigning multiple domains (and possibly multiple vocabularies themselves, see #99) to an operator means that we'd need:

1. A second delimiter character in the CSVs to delimit the domains/vocabs per operator row
2. Have separate files for operators, vocabs, and domains (essentially, CSV files that look a lot like tables in a relational database)
3. Use a JSON or YAML representation for each operator, though this format leads to some amount of duplication as well.

Do we plan to manage this/these files ourselves?  I imagine so.  In that case, I'd prefer option 2.

**Comment by markdanese** [comment]
JSON/YAML is fine.  This isn't going to be too nested to understand.

**Comment by markdanese** [comment]
I am also fine with option 3.  Sometimes it is easier to understand when things are together.  But at some point it gets too confusing.

**Comment by aguynamedryan** [comment]
READ is not going to be replaced by this operator.  The READ operator uses the `mapping_type` column in the source_to_concept_map table to determine which tables to query.  Unless we list each code and its domain in these files, we can't accommodate that kind of operation in this operator.

Summary: multi-domain vocabularies aren't supported by this operator and most likely will never be.

Soooooooo, we only have multi-vocabulary operators to worry about (#99).  Since these are fairly uncommon we can do one of two things:

1. Create one-off operators that subclass the vocabulary operator (think CPT/HCPCS) operator
2. Create an operator that can combine multiple vocabularies by using multiple instances of #106's operator.

Ima lean towards option 2.  We could probably even have a separate CSV file that lists the name of an operator and a vocab ID and generate and roll the vocabs up by operator and create metadata for each unique operator, much like #106, but specially designed for multiple vocabularies.

**Comment by aguynamedryan** [comment]
I've added a "domain" column to the CSV file, filled it out for most OMOP-derived vocabularies, and wired it into #106.

If an operator doesn't have a domain assigned, it won't show up as an operator for omopv4_plus because the generic operator wouldn't know what table to search.

(8fa8abca94d2c1fff24a2da2282755b8f5064677)

**Comment by jenniferduryea** [comment]
Per Ryan, he tested this and it's working.  Leaving this until we receive Amgen's test CSV file to confirm it works.

**Comment by jenniferduryea** [comment]
Please see Amgen's csv file in the following folder: ...\AMG (Jigsaw) Installation and JAR\Support\Vocabulary CSV Files.  Please use this for testing.

**Comment by jenniferduryea** [comment]
Just a note that @aguynamedryan has done some preliminary tests and confirmed that the Diagram Editor will add a new operator for every new entry in the CSV.

**Comment by jenniferduryea** [comment]
@aguynamedryan please upload Amgen's CSV file so that we can ensure:
 * all of the new vocabularies get an operator
 * display for all new operators work
 * colors look ok
 * sql code is correct

**Comment by jenniferduryea** [comment]
Ryan uploaded the file and the Diagram editor showed multiple selection operators.  Looks good.  Closing out.

**Comment by jenniferduryea** [comment]
confirmed all operators in csv file have correct operator color, query correct vocabulary_ids, query correct domains. Closing out.
