### ISSUE TITLE
Issue When all Read Codes Have a Domain

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#147]
Studies are failing when algorithms use Read codes that all have a domain assigned.

**Comment by aguynamedryan** [comment]
I'd written the Read operator so that if there were any codes remaining that didn't have a match in the `source_to_concept_map` table, we'd treat them as observations.

I hadn't considered the prospect that all codes would match, so ConceptQL still added any leftovers, which was a set of empty codes, to be found in the `observation` table, causing ConceptQL to blow up when it got an empty set of codes (from itself no less ;-)

**Comment by jenniferduryea** [comment]
Created an algorithm with one read code (F29y411) that is assigned to "condition" from the SCM.  I ran the study "test all assigned read codes" against synpuf250 and the study did not fail.  It completed successfully.

I also created another algorithm that contained one assigned read code (F29y411) and one unassigned read code (FakeRead123).  I ran the study "test one unassigned read code" and the study completed without errors.

I created antoher algorithm that contained only one unassigned code (FakeRead123) and ran the study "test unassigned read code only" and the study completed without errors.

I consider this tested.
