### ISSUE TITLE
Operators that use provenance information needs to use the mapping table

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#218]
source_type_concept_ids and provenance_concept_ids change after every (gdm) ETL into for a new dataset.  We need conceptql to look at the mapping table to map "jigsaw vocabulary" codes to these new concept_ids for every dataset.  

Currently, Oneintwoout and Provenance Filter operators look for provenance concept_ids and are failing against BTC database because the hardcoded provenance concept_ids ConceptQL uses are invalid against this new dataset.

Tagging @marc-outins for implementation and @aguynamedryan for oversight.  Please comment on what the Jigsaw vocabulary entails and how these provenance filters will work against OMOP v4.5+ datsets.

**Comment by aguynamedryan** [comment]
Just a few thoughts on this.

### Supporting mappings for both GDM _and_ OMOP

ConceptQL is burdened by supporting (at least) two data models: OMOPv4.5+ and GDM

Until now, ConceptQL hasn't needed to fetch concept_ids for OMOP datasets because we always use source values.  The Provenance operator broke this approach to OMOP -- ConceptQL needed the concept_ids, along with "descendants" of those concept_ids for various provenance types.

To work around this issue, I originally created a small YAML file that contained the OMOP-based, provenance-related concept_ids we needed and we dodged the issue for a while.  But now that we're introducing (proper) support for GDM, we'd like to rely on GDM's mappings table (or a derivative of that table I like to call "ancestors") to dynamically collect all appropriate concept_ids for a given provenance entry.

We'd also like to ensure that, moving forward, provenance specified using the original OMOP names for provenance, e.g. inpatient_header are still supported by the Provenance operator under both OMOP and GDM, and that future provenance types, say, "EHR allergy list" can be introduced and supported by not just GDM, but perhaps OMOP.

This is doable, but seems to be confusing.

We simply need to create a set of mappings for OMOP-related provenance concepts and stick them in Lexicon.  Here's a sample of a few concepts, their mappings, and then the ancestor table:

![blank diagram](https://user-images.githubusercontent.com/117722/52814732-af1e6600-3051-11e9-8ab8-57a19cd8bded.png)

#### OMOP Mappings

Mappings Table

| concept_id_1 | relationship_id | concept_id_2 |
| ----- | ----- | ---- |
| 8 | is a | 1 |
| 7 | is a | 6 |
| 7 | is a | 8 |
| 6 | is a | 1 |
| 5 | is a | 3 |
| 4 | is a | 8 |
| 4 | is a | 3 |
| 3 | is a | 1 |


### Ancestors Table

Just to clarify what I mean by "ancestors" table, it is a table that we can automatically generate based on our mappings table.  The table isn't particularly useful to humans, but it is a convenient table to have when a relational database would otherwise need to recursively walk down a set of relationships.  This kind of walk requires a recursive subquery, something that is expensive to run, and isn't even supported in some RDBMS systems (*cough* Impala *cough*).  The table just flattens the mappings table so that we can ask the ancestors table for all descendants of a particular concept.

![ancestors table](https://user-images.githubusercontent.com/117722/52814781-d1b07f00-3051-11e9-87b9-8887e21faf02.png)

Ancestors Table

| ancestor_id | descendant_id |
| ------- | ------ |
| 1 | 1 |
| 1 | 3 |
| 1 | 4 |
| 1 | 5 |
| 1 | 6 |
| 1 | 7 |
| 1 | 8 |
| 3 | 4 |
| 3 | 5 |
| 4 | 4 |
| 5 | 5 |
| 6 | 6 |
| 6 | 7 |
| 7 | 7 |
| 8 | 4 |
| 8 | 7 |
| 8 | 8 |

You'll notice that the ancestors table has rows where the ancestor_id and descendant_id share the same ID.  This just makes the query easier for ConceptQL where if we ask for all descendants of, say "inpatient" we get back the "inpatient"'s ID in the collection of IDs so we include that as part of the collection of provenance IDs we're interested in filtering by.

## Lexicon Confusion

GDM datasets are supposed to carry their own mappings and vocabularies tables to keep the dataset completely self-contained, much like OMOP datasets contain the vocabulary files that were used during the ETL process.

Originally, Lexicon was created so ConceptQL could validate code lists for the diagram editor.  That was it.

But Lexicon now seems to be moving into the territory of housing our "universal vocabularies" as we'd discussed but never formally agreed to.

That's fine as well, and Lexicon is probably the only place that our custom mappings of OMOP concepts can live.  That should also be fine, because for OMOP, there should only be one viable mapping for things like provenance and we can maintain that mapping on behalf of OMOP should they introduce more provenance concepts.

GDM datasets contain their own mappings (and derived ancestors tables) so ConceptQL should be programmed to attempt to read from these tables rather than Lexicon's.  Should a dataset not have a mappings or ancestors table, like an OMOP dataset, we should fall back to using the tables provided in Lexicon.

**Comment by aguynamedryan** [comment]
I decided to look at how Amgen is using Provenance to determine what options we need to support moving forward.

I downloaded their most recent backup of jigsaw-prd and searched for any use of the Provenance operator in their algorithms.  I then grabbed all the arguments fed to this operator and collapsed them down into the unique values used.  Here's the list, with number of occurrences listed first:

| num | argument |
| --- | -------- |
| 1 | 38000183 |
| 1 | 38000184 |
| 1 | 38000199 |
| 1 | 38000200 |
| 1 | 38000248 |
| 1 | 38000249 |
| 1 | 38000250 |
| 1 | 38000251 |
| 1007 | carrier_claim |
| 1105 | inpatient |
| 17 | inpatient_primary |
| 15 | inpatient_primary_or_first |
| 1006 | outpatient |
| 2150 | provenance |

The concept IDs that are listed there all come from one operator in one algorithm and are the concept IDs for "first" or "primary" within various inpatient settings, meaning they are equivalent to "inpatient_primary_or_first"

So, it looks like we don't ever use positional arguments (e.g. inpatient_detail_2) so those can be dropped.

I seems like we could update the Provenance operator to be a dropdown list with the three following options:

- carrier_claim
- inpatient
- outpatient

Then either one or two check boxes:
Just one:
-  "include primary or first"

As two:
1. "Include primary"
2.  "Include first"

Thoughts?

**Comment by jenniferduryea** [comment]
I think this works for OMOP.  My only question is, do we want to include more selections for GDM files like hospice, dme, etc?  We can make those "gdm only" options in the operator?  

If you wouldn't mind doing the same check on what is used in the provenance operator for our gdm server (outins.jsaw.io), you may see different provenances.

**Comment by aguynamedryan** [comment]
@jenniferduryea, I found much the same as we had in jigsaw-prd, except where we used a GDM-specific concept ID for DME.

When I first created the Provenance operator, there were three ideas associated with provenance and OMOP had smashed them all together into a single value:

- File type (inpatient, outpatient, claims, EHR, etc)
- "Source" type (primary diagnosis, admission diagnosis, etc)
- Position (diagnosis 1, diagnosis 7, etc)

I've already mentioned above that it seems safe to avoid "position" entirely.  No one is using it at the moment.

"Source" is somewhat like "position" but with names rather than numbers, and people do seem to be using that one.

@jenniferduryea pointed out that there are possibly more file types we want to support.  @marc-outins explained to me that there may be more "source" types than just "primary" or "first" that we want to support.

@marc-outins also reminded me that we'd already decided drop downs were a Bad Idea because then the Provenance operator wouldn't allow users to select something like "inpatient" AND "claims" at the same time.

We could move to checkboxes or a multi-select box to allow users to select multiple file and source types in the same operator.  I'm not sure how visually stunning either option would be though.

For the time being, we'll leave the free-form text area as is and find add any words that have no matching "file" or "source" type to a warning for the Provenance operator.  Each "argument" can contain a file and/or source type and arguments are delimited by a comma.  Arguments using underscores will be grandfathered in, as will "inpatient_first_or_primary"

From here on out, I consider any of the following to be valid entries:

- inpatient
  - all events from an inpatient file
- inpatient, claims
  - all events from an inpatient or carrier claims file
- inpatient, carrier claims
  - all events from an inpatient or carrier claims file
- outpatient, inpatient primary
  - all events from (an outpatient file) or (inpatient file as primary diagnosis/procedure)
- primary
  - all events whose "source" is reported as "primary"
- admission
  - all events whose "source" is reported as "primary"
- inpatient admission
  - all events whose "source" is reported as "admission" from an "inpatient" file

**Comment by aguynamedryan** [comment]
I think in the near? future, we should create separate "file type" and "source type" operators and deprecate Provenance.  Splitting out these two filters will make it much clearer what is happening in a ConceptQL statement.  

I might actually implement Provenance so that it uses these two new operators under the hood.

**Comment by jenniferduryea** [comment]
So we may need to change some info on this ticket about the role that lexicon is going to be used.  But in any case, I am testing the Provenance Filter on chisel.jsaw.io.  I can confirm the following:
- provenance filter set to omop type_concept_id value, Jigsaw will find the codes with that omop type_concept_id against omop data source
- provenance filter set to omop type_concept_id value, Jigsaw will not find any codes when run against gdm data source
- provenance filter set to Jigsaw vocabulary value "carrier_claim", Jigsaw will find the codes with that have omop type_concept_id of "carrier" against omop data source
- provenance filter set to Jigsaw vocabulary value "carrier_claim", Jigsaw will find the codes with source_type =  against gdm data context.source_type = "synpuf carrier claims"
- provenance filter set to gdm source_type_id value, Jigsaw will find the codes with that gdm source_type concept_id against gdm data source
- provenance filter set to gdm source_type_id value, Jigsaw will not find any codes when run against omop data source

I think this is working as intended.  At least for Provenance.  I think I need to test 1in2out next.

**Comment by jenniferduryea** [comment]
works as intended for gdm.  Closing.
