### ISSUE TITLE
Operator metadata quirks

### ISSUE THREAD

**Issue by nickawalsh** [outcomesinsights/conceptql#38]
A few things we noticed during JAM integration:

* `one_in_two_out` has a `number` type on a parameter - should that be `float` or `integer` instead?
* The newly added categories are in their own nested array--would you like this to be supported for future possibilities, or could they just be strings in the category array? I think we touched on this during a call, but I can't remember the resolution.
* A few operators (`count`, `numeric`, `sum`) currently a missing categories, and as such aren't included in the listing.

**Comment by aguynamedryan** [comment]
I just pushed some changes to the master branch that should address the issues you list above.

- I changed `number` to `integer`
- Feel free to flatten the array since we don't have sub-categories and don't see a need to support them in the near term
- Operators without categories should not be included in the listing
- See [this document about metadata](https://github.com/outcomesinsights/conceptql/blob/master/doc/metadata.md) for more details

**Comment by jenniferduryea** [comment]
Is this still an open issue?  Please close this out unless there is something still pending here.  Thanks!
