### ISSUE TITLE
Add carrier_header and carrier_detail to the "primary" condition_type variable/shortcut

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#65]
Include carrier_header first position (concept_id = 45756835) and carrier_detail first position (concept_id = 45756843) into the definition of "primary".

**Comment by aguynamedryan** [comment]
Do we want to remove the condition_type operator and replace it with the Provenance (#55) operator instead of updating the condition_type operator?

**Comment by jenniferduryea** [comment]
I'm ok with that.

**Comment by jenniferduryea** [comment]
Invalidating this ticket since there are no concept_ids that have a "primary" position for carrier and outpatient claims.  If the shortcut was "primary", then it should only include type_concept_ids that mention "primary".  Will create a new ticket to create a shortcut called "primary and first" and will include primary and first positions for inpatient, carrier and outpatient type_concept_ids.
